#!/usr/bin/env python3
# vpsman
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent))

from vps_manager.ui import VPSManagerApp

if __name__ == "__main__":
    app = VPSManagerApp()
    app.run()
